import org.apache.tools.ant.taskdefs.condition.Os

def getBuildParameters(base) {
  def target = project.findProperty('nativeTarget') ?: System.getenv('NATIVE_TARGET')

  if (target != null) {
    if (target == "win-x86-64") {
      return [
          'identifier': "win-x86-64",
          'library': "${base}.dll",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release', '-A', 'x64'],
          'buildArguments': ['--config', 'Release'],
          'env': [:]
      ]
    } else if (target == "win-x86") {
      return [
          'identifier': "win-x86",
          'library': "${base}.dll",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release', '-A', 'Win32'],
          'buildArguments': ['--config', 'Release'],
          'env': [:]
      ]
    } else if (target == "darwin") {
      return [
          'identifier': 'darwin',
          'library': "lib${base}.dylib",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64'],
          'buildArguments': [],
          'env': [:]
      ]
    } else if (target == "linux-x86") {
      return [
          'identifier': "linux-x86",
          'library': "lib${base}.so",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_SYSTEM_NAME=Linux', '-DCMAKE_SYSTEM_PROCESSOR=i686', '-DCMAKE_C_FLAGS=-m32', '-DCMAKE_CXX_FLAGS=-m32', '-DCMAKE_SHARED_LINKER_FLAGS=-m32'],
          'buildArguments': [],
          'env': [:]
      ]
    } else if (target == "linux-armhf" || target == "linux-arm") {
      def toolchainArgs = []
      if (!Os.isFamily(Os.FAMILY_WINDOWS) && !Os.isFamily(Os.FAMILY_MAC) && System.getProperty("os.arch") != "arm" && System.getProperty("os.arch") != "aarch64") {
        toolchainArgs = [
            '-DCMAKE_SYSTEM_NAME=Linux',
            '-DCMAKE_SYSTEM_PROCESSOR=arm',
            '-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc',
            '-DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++',
            '-DCMAKE_C_FLAGS=-march=armv7-a -mfpu=neon -mfloat-abi=hard',
            '-DCMAKE_CXX_FLAGS=-march=armv7-a -mfpu=neon -mfloat-abi=hard'
        ]
      }
      return [
          'identifier': target,
          'library': "lib${base}.so",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release'] + toolchainArgs,
          'buildArguments': [],
          'env': [:]
      ]
    } else if (target == "linux-aarch32") {
      def toolchainArgs = []
      if (!Os.isFamily(Os.FAMILY_WINDOWS) && !Os.isFamily(Os.FAMILY_MAC) && System.getProperty("os.arch") != "arm" && System.getProperty("os.arch") != "aarch64") {
        toolchainArgs = [
            '-DCMAKE_SYSTEM_NAME=Linux',
            '-DCMAKE_SYSTEM_PROCESSOR=arm',
            '-DCMAKE_C_COMPILER=arm-linux-gnueabi-gcc',
            '-DCMAKE_CXX_COMPILER=arm-linux-gnueabi-g++',
            '-DCMAKE_C_FLAGS=-march=armv7-a -mfpu=neon -mfloat-abi=softfp',
            '-DCMAKE_CXX_FLAGS=-march=armv7-a -mfpu=neon -mfloat-abi=softfp'
        ]
      }
      return [
          'identifier': "linux-aarch32",
          'library': "lib${base}.so",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release'] + toolchainArgs,
          'buildArguments': [],
          'env': [:]
      ]
    } else if (target == "linux-aarch64") {
      def toolchainArgs = []
      if (!Os.isFamily(Os.FAMILY_WINDOWS) && !Os.isFamily(Os.FAMILY_MAC) && System.getProperty("os.arch") != "aarch64") {
        toolchainArgs = [
            '-DCMAKE_SYSTEM_NAME=Linux',
            '-DCMAKE_SYSTEM_PROCESSOR=aarch64',
            '-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc',
            '-DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++',
            '-DCMAKE_C_FLAGS=-march=armv8-a',
            '-DCMAKE_CXX_FLAGS=-march=armv8-a'
        ]
      }
      return [
          'identifier': "linux-aarch64",
          'library': "lib${base}.so",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release'] + toolchainArgs,
          'buildArguments': [],
          'env': [:]
      ]
    } else if (target == "linux-musl-aarch64") {
      def toolchainArgs = []
      if (!Os.isFamily(Os.FAMILY_WINDOWS) && !Os.isFamily(Os.FAMILY_MAC) && System.getProperty("os.arch") != "aarch64") {
        toolchainArgs = [
            '-DCMAKE_SYSTEM_NAME=Linux',
            '-DCMAKE_SYSTEM_PROCESSOR=aarch64',
            '-DCMAKE_C_COMPILER=aarch64-linux-musl-gcc',
            '-DCMAKE_CXX_COMPILER=aarch64-linux-musl-g++',
            '-DCMAKE_C_FLAGS=-march=armv8-a',
            '-DCMAKE_CXX_FLAGS=-march=armv8-a'
        ]
      }
      return [
          'identifier': "linux-musl-aarch64",
          'library': "lib${base}.so",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release'] + toolchainArgs,
          'buildArguments': [],
          'env': [:]
      ]
    } else {
      return [
          'identifier': target,
          'library': "lib${base}.so",
          'setupArguments': ['-DCMAKE_BUILD_TYPE=Release'],
          'buildArguments': [],
          'env': [:]
      ]
    }
  }

  if (Os.isFamily(Os.FAMILY_WINDOWS)) {
    return [
        'identifier': "win-x86-64",
        'library': "${base}.dll",
        'setupArguments': ['-DCMAKE_BUILD_TYPE=Release', '-A', 'x64'],
        'buildArguments': ['--config', 'Release'],
        'env': [:]
    ]
  } else if (Os.isFamily(Os.FAMILY_MAC)) {
    return [
        'identifier': 'darwin',
        'library': "lib${base}.dylib",
        'setupArguments': ['-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64'],
        'buildArguments': [],
        'env': [:]
    ]
  } else {
    return [
        'identifier': "linux-x86-64",
        'library': "lib${base}.so",
        'setupArguments': ['-DCMAKE_BUILD_TYPE=Release'],
        'buildArguments': [],
        'env': [:]
    ]
  }
}

def getHomeDirectory() {
  def directory = file(System.getProperty('java.home'))
  return directory.name == 'jre' ? directory.parentFile.absolutePath : directory.absolutePath
}

def createBuildTask(tasksHolder, config) {
  def parameters = getBuildParameters(config.name)
  def buildDirectory = "${config.buildBase}/${parameters.identifier}"
  def distDirectory = "${config.projectBase}/dist/${parameters.identifier}"
  def deployDirectory = "${config.deployBase}/src/main/resources/natives/${parameters.identifier}"
  def taskBase = "${config.name}-64"

  parameters.env.put('DIST_DIR', distDirectory)
  parameters.env.put('JAVA_HOME', getHomeDirectory())

  def setupTask = tasksHolder.create("${taskBase}-setup", Exec) {
    doFirst {
      if (config.setupDoFirst) {
        config.setupDoFirst(config)
      }

      file(buildDirectory).with {
        it.deleteDir()
        it.mkdirs()
      }
    }

    workingDir buildDirectory
    executable 'cmake'
    args(parameters.setupArguments + ['../..'])
    parameters.env.each { k, v ->
      environment k, v
    }
  }

  def buildTask = tasksHolder.create("${taskBase}-build", Exec) {
    workingDir buildDirectory
    executable 'cmake'
    args(['--build', '.'] + parameters.buildArguments)
    parameters.env.each { k, v ->
      environment k, v
    }
  }

  def deployTask = tasksHolder.create("${taskBase}-deploy") { doLast {
    copy {
      from distDirectory
      into deployDirectory
      include parameters.library
    }
  }}

  tasksHolder.create("${taskBase}-deploy-only") { doLast {
    copy {
      from distDirectory
      into deployDirectory
      include parameters.library
    }
  }}

  if (config.setupDependency) {
    setupTask.dependsOn(config.setupDependency)
  }

  buildTask.dependsOn(setupTask)
  deployTask.dependsOn(buildTask)
  config.compileTask.dependsOn(deployTask)

  if (!file("${deployDirectory}/${parameters.library}").exists()) {
    config.checkTask.dependsOn(deployTask)
  }
}

ext.createBuildTask = { tasksHolder, config -> createBuildTask(tasksHolder, config) }
