plugins {
  id 'java'
  id 'maven-publish'
}

version = '1.0.3'
ext.moduleName = 'lavaplayer-natives'


task sourceJar(type: Jar) {
  archiveClassifier = 'sources'
  from sourceSets.main.allJava
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      groupId rootProject.group
      artifactId moduleName
      from components.java

      artifact sourceJar
    }
  }
}
